global:
    registry: 'randommatchakscr.azurecr.io'

ingress:
    annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    labels: {}
    host: ''
    tlsSecretName: ''

frontend:
    replicas: 1
    port: 8080
    image:
        repo: randommatch/api-core
        tag: 93d5faa270eb4bcc177c2a86d749ffd06c719cb2-2606436253
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 300Mi
