global:
    registry: 'randommatchakscr.azurecr.io'

ingress:
    labels: {}
    host: ''
    tlsSecretName: ''

ui:
    replicas: 1
    port: 80
    image:
        repo: randommatch/ui
        tag: changeme

backend:
    replicas: 1
    port: 8080
    image:
        repo: randommatch/api-core
        tag: 93d5faa270eb4bcc177c2a86d749ffd06c719cb2-2606436253
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 300Mi

matchdb:
    image:
        repo: neo4j
        tag: 4.4.8
    resources:
        requests:
            cpu: 500m
            memory: 512Mi
        limits:
            cpu: 500m
            memory: 512Mi
