---
apiVersion: v1
kind: Service
metadata:
  name: back-end
  labels:
    name: back-end
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.backend.port }}
  selector:
    name: back-end

