---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      name: back-end
  template:
    metadata:
      labels:
        name: back-end
    spec:
      containers:
      - name: back-end
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.backend.image.repo }}:{{ .Values.backend.image.tag }}
        resources:
{{ toYaml .Values.backend.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: GIN_MODE
          value: "release"
        - name: SES_KEY_ID
          value: {{ .Values.backend.aws_ses.keyid }}
        - name: SES_KEY_SECRET
          value: {{ .Values.backend.aws_ses.keysecret }}
        - name: DB_HOST
          value: {{ .Values.backend.dbhost }}
        - name: NEO4J_AUTH
          value: {{ .Values.matchdb.creds }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health-check
            port: {{ .Values.backend.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health-check
            port: {{ .Values.backend.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
