---
apiVersion: v1
kind: Service
metadata:
  name: match-db
  labels:
    name: match-db
spec:
  ports:
    # the port that this service should serve on
  - port: 7687
    targetPort: 7687
  selector:
    name: match-db