---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: neo4j-azurefile-csi
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=7474
  - gid=7474
  - mfsymlinks
  - nobrl
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - nosharesock # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
parameters:
  skuName: Standard_LRS

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-azurefile-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: neo4j-azurefile-csi
  resources:
    requests:
      storage: 1Gi