on:
  push:
    branches:
    - main
    paths:
    - 'iac/terraform/**'
    - '.github/workflows/workflow.terraform.deploy.yml'

jobs:
  resource_prefix:
    runs-on: ubuntu-latest
    name: "resource prefix"
    outputs:
      # Set output for next job
      RESOURCES_PREFIX: ${{ steps.resources_prefix.outputs.result }}
    steps:
      # Get RESOURCES_PREFIX based on the repo name
      - name: Get repo name
        uses: actions/github-script@v5
        id: resources_prefix
        with:
          result-encoding: string
          script: return context.repo.repo.toLowerCase()

      # Usage for current job: ${{ steps.resources_prefix.outputs.result }}
  build:
      needs: [resource_prefix]
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: 'Az CLI login'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: 'Terraform validation and deployment'
          env:
            TFSTATE_KEY: ${{ secrets.TFSTATE_KEY }}
            TFSTATE_RESOURCES_GROUP_NAME: ${{ secrets.TFSTATE_RESOURCES_GROUP_NAME }}
            TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}
            TFSTATE_STORAGE_CONTAINER_NAME: ${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}
          run: |
            cd ./iac/terraform
            bash -x generate_sp.sh  "${{ secrets.ARM_CLIENT_ID }}" "${{ secrets.ARM_CLIENT_SECRET }}" "${{ secrets.ARM_SUBSCRIPTION_ID }}" "${{ secrets.ARM_TENANT_ID }}"
            bash deploy.sh -l ${{ secrets.LOCATION }} -u 220628 -r  ${{ needs.resource_prefix.outputs.RESOURCES_PREFIX }}