on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
    - main
    paths:
    - 'iac/terraform/**'
    - '.github/workflows/workflow.terraform.pr.yml'
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: 'Validate format of the Iac'
          run: | 
            cd ./iac/terraform 
            terraform fmt -check
            terraform init -backend=false
            terraform validate
