on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'application/core/**'
      - '.github/workflows/workflow.build.core.yml'

  pull_request:
    branches: [ "main" ]
    paths:
      - 'application/core/**'
      - '.github/workflows/workflow.build.core.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build    
      run: |
        cd ./application/core
        go get
        go build

    - name: Test
      id: test
      continue-on-error: false
      run: |
       cd ./application/core
       GIN_MODE=release go test -v
    
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build image for Azure container registry'
      run: |
        cd ./application/core
        az acr build --image randommatch/api-core:${{ github.sha }}-${{ github.run_id }} \
        --registry randommatchakscr \
        --file ./Dockerfile .
    
    - name: 'Package helm chart and save it to Azure container Registry'
      run: |
        cd ./application/match-chart
        helm package .
        echo ${{ secrets.ARM_CLIENT_SECRET}} | helm registry login randommatchakscr.azurecr.io \
        --username ${{ secrets.ARM_CLIENT_ID }} --password-stdin
        az acr repository delete --name randommatchakscr --image helm/match-chart:0.1.0 --yes || true
        helm push match-chart-0.1.0.tgz oci://randommatchakscr.azurecr.io/helm
        az acr repository show --name randommatchakscr  --repository helm/match-chart
        az aks get-credentials --resource-group randommatchaksrg --name randommatchaksk8s
        helm install myhelmtest oci://randommatchakscr.azurecr.io/helm/match-chart --version 0.1.0 --namespace randommatch --create-namespace
        kubectl get pods --namespace randommatch
        helm uninstall myhelmtest --namespace randommatch
        kubectl delete namespace randommatch


# helm install myhelmtest oci://$ACR_NAME.azurecr.io/helm/hello-world --version 0.1.0
# helm uninstall myhelmtest
# az acr repository delete --name $ACR_NAME --image helm/hello-world:0.1.0
# https://docs.microsoft.com/en-us/azure/aks/kubernetes-helm
# https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos

