on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'application/core/**'
      - '.github/workflows/workflow.build.core.yml'

  pull_request:
    branches: [ "main" ]
    paths:
      - 'application/core/**'
      - '.github/workflows/workflow.build.core.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build    
      run: |
        cd ./application/core
        go get
        go build

    - name: Test
      id: test
      continue-on-error: false
      run: |
       cd ./application/core 
       GIN_MODE=release go test -v
    
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build image for Azure container registry'
      run: |
        ls
        az acr build --image randommatch/api-core:${{ github.sha }}${{ github.run_id }} \
        --registry randommatchakscr \
        --build-arg build_version=${{ github.sha }}${{ github.run_id }} --file ./Dockerfile .